let cfg={},products=[],cart=JSON.parse(localStorage.getItem('saree_cart')||'[]'),chatState={};
const $=id=>document.getElementById(id),money=n=>'৳'+Number(n||0).toLocaleString('en-BD');
async function api(url,opt={}){const r=await fetch(url,opt);const j=await r.json().catch(()=>({error:'Server returned an invalid response.'}));if(!r.ok)throw Error(j.error||'Request failed');return j}
async function loadSettings(){cfg=await api('/api/settings');document.body.dataset.theme=cfg.theme||'luxury';document.documentElement.style.setProperty('--gold',cfg.primary_color||'#d8a449');$('tagline').textContent=cfg.store_tagline||'Discover our exclusive collection of premium sarees for every occasion.';$('qDelivery').textContent='Delivery Time';$('qStore').textContent='Store Info';$('qOrder').textContent='Order Now'}
async function loadProducts(){products=await api('/api/products?search='+encodeURIComponent($('search').value||''));renderProducts()}
function renderProducts(){ $('products').innerHTML=products.map(p=>`<article class="product"><div class="productImg">${p.image?`<img src="${p.image}" alt="${safe(p.name)}">`:'SAREE'}</div><div class="productInfo"><small>${safe(p.category)}</small><h3>${safe(p.name)}</h3><p>${safe(p.description)}</p><div class="price">${money(p.price)}${p.old_price?`<span class="old">${money(p.old_price)}</span>`:''}</div><div class="actions"><button onclick="add(${p.id})">ADD TO CART</button><button class="primary" onclick="orderNow(${p.id})">ORDER NOW</button></div></div></article>`).join('')||'<p>No products found.</p>'}
function safe(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function saveCart(){localStorage.setItem('saree_cart',JSON.stringify(cart));$('count').textContent=cart.reduce((n,x)=>n+x.qty,0);renderCart()}
function add(id){let x=cart.find(a=>a.id===id);x?x.qty++:cart.push({id,qty:1});saveCart();openCart()}
function orderNow(id){cart=[{id,qty:1}];saveCart();checkout()}
function openCart(){renderCart();$('cart').classList.add('open')}function closeCart(){$('cart').classList.remove('open')}
function renderCart(){let total=0;$('cartItems').innerHTML=cart.map(x=>{let p=products.find(p=>p.id===x.id);if(!p)return'';total+=p.price*x.qty;return`<div class="cartRow"><span>${safe(p.name)} × ${x.qty}</span><b>${money(p.price*x.qty)}</b></div>`}).join('')||'<p>Your cart is empty.</p>';$('cartTotal').textContent=money(total)}
async function checkout(){if(!cart.length)return alert('Your cart is empty.');cfg=await api('/api/settings');const opts=[];if(cfg.bkash_number)opts.push('<option>bKash</option>');if(cfg.nagad_number)opts.push('<option>Nagad</option>');if(cfg.rocket_number)opts.push('<option>Rocket</option>');if(cfg.cod_enabled==='true')opts.push('<option>COD</option>');$('paymentMethod').innerHTML=opts.join('');$('checkoutItems').innerHTML=cart.map(x=>{const p=products.find(p=>p.id===x.id);return p?`<p>${safe(p.name)} × ${x.qty} — ${money(p.price*x.qty)}</p>`:''}).join('');$('checkoutMessage').textContent='';$('checkoutModal').style.display='flex';$('paymentMethod').onchange=paymentInfo;paymentInfo()}
function closeCheckout(){$('checkoutModal').style.display='none'}
function paymentInfo(){const m=$('paymentMethod').value;const n=m==='bKash'?cfg.bkash_number:m==='Nagad'?cfg.nagad_number:m==='Rocket'?cfg.rocket_number:'';$('paymentInfo').textContent=m==='COD'?'Cash on Delivery selected.':(n?`${m} Send Money: ${n}`:'Admin has not configured this payment number yet.')}
async function placeOrder(){try{const method=$('paymentMethod').value;if(!method)throw Error('No payment method is available.');const tx=$('transactionId').value.trim();if(method!=='COD'&&!tx)throw Error('Transaction ID is required for online payment.');const j=await api('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customer_name:$('customerName').value,phone:$('customerPhone').value,address:$('customerAddress').value,payment_method:method,transaction_id:tx,items:cart})});$('checkoutMessage').innerHTML=`<p class="success">Order successful!<br>Order ID: <b>${j.order_id}</b><br>Total: ${money(j.total)}</p>`;cart=[];saveCart()}catch(e){$('checkoutMessage').textContent=e.message}}
async function trackOrder(){try{const o=await api('/api/orders/'+encodeURIComponent($('trackCode').value.trim()));$('trackResult').innerHTML=`<div class="agent"><b>${o.order_code}</b><br>Customer: ${safe(o.customer_name)}<br>Status: <b>${safe(o.status)}</b><br>Total: ${money(o.total)}</div>`}catch(e){$('trackResult').textContent=e.message}}
async function loadAgents(){const a=await api('/api/agents');$('agentsList').innerHTML=a.map(x=>`<div class="agent"><h3>${safe(x.name)}</h3><p>${safe(x.phone)}</p>${x.whatsapp?`<a target="_blank" href="https://wa.me/${encodeURIComponent(x.whatsapp.replace(/\D/g,''))}">WhatsApp</a>`:''}${x.messenger?`<a target="_blank" href="${safe(x.messenger)}">Messenger</a>`:''}</div>`).join('')||'<p>No active agents.</p>'}
function toggleChat(){const c=$('chat');c.classList.toggle('open');if(c.classList.contains('open')&&!$('msgs').children.length)addMsg('bot',cfg.chatbot_store||'Welcome to SAREE Premium. How can I help?')}
function addMsg(w,t){const d=document.createElement('div');d.className='msg '+(w==='me'?'me':'');d.textContent=t;$('msgs').appendChild(d);$('msgs').scrollTop=$('msgs').scrollHeight}
function quick(type){const text=type==='delivery'?(cfg.chatbot_delivery||'What is the delivery time?'):type==='store'?(cfg.chatbot_store||'What do you sell?'):(cfg.chatbot_order||'I want to order now');$('chatText').value=text;sendChat()}

async function matchImage(){const f=$('customerImage').files[0];if(!f)return alert('Choose a product image first.');addMsg('me','I sent a product image for matching.');const fd=new FormData();fd.append('image',f);try{const r=await fetch('/api/catalog-match',{method:'POST',body:fd});const j=await r.json();if(!r.ok)throw Error(j.error||'Image matching failed.');if(!j.matches.length)return addMsg('bot','I could not find a confident catalog match. Please tell me the saree name or ask an agent.');j.matches.forEach(x=>addMsg('bot',`${x.product.name} — ${money(x.product.price)}\nMatch confidence: ${Math.round(Number(x.confidence||0)*100)}%\n${x.reason||''}`));}catch(e){addMsg('bot',e.message)}}
async function sendChat(){const i=$('chatText'),m=i.value.trim();if(!m)return;i.value='';addMsg('me',m);try{const r=await api('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:m,state:chatState})});chatState=r.state||chatState;addMsg('bot',r.reply);if(chatState.confirmed){if(confirm('Confirm this order?')){const order=await api('/api/chat/confirm-order',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirmed:true,customer_name:chatState.customer_name,phone:chatState.phone,address:chatState.address,payment_method:chatState.payment_method||'COD',transaction_id:chatState.transaction_id||'',items:[{id:Number(chatState.product_id),qty:Number(chatState.quantity||1)}]})});addMsg('bot',`Order confirmed: ${order.order_id}\nTotal: ${money(order.total)}`);chatState={}}}}catch(e){addMsg('bot',e.message)}}
(async()=>{try{await loadSettings();await loadProducts();await loadAgents();saveCart()}catch(e){console.error(e)}})();
